### ISSUE TITLE
Incoming feature: multi-file support

### ISSUE THREAD

**Issue by esbena** [wala/jsdelta#22]
JSDelta is currently only able to do reductions for a single source
file at a time.  We will soon be developing support for exploring
reductions of multiple files in a single run of JSDelta, and we will
make a pull request when the feature is done.

The feature is JavaScript independent, and any delta-debugger could
make use of it, but I am not aware of any available solutions. Are
you?

If not, then we will implement it from scratch according to the
following plan, input is welcome.

# Plan

Conceptually, two new AST-nodes will be added: directories and files.

This means that:

- directories will be treated as statements currently are
  (i.e. "binary-search" and recursive deletions of files/directories)

- files will be treated as expressions currently are (i.e. individual
  mutations, but through an application of the current JSDelta)

---

Practically, each iteration will be a done on a full copy of the
latest successful reduction (we might need to delete the unsuccessful
copies for space reasons). File- and directory-names probably needs to
be kept unchanged.

---

Implementation-wise, JSDelta will need to remember (these two are
currently the same thing):

- where the "main-file" is relative to the root directory
- which file/directory that is being reduced

**Comment by msridhar** [comment]
This sounds great!  I don't know of any immediately usable off-the-shelf solution for this problem.  Based on [this blog post](http://blog.regehr.org/archives/1405), I think [C-Reduce](https://github.com/csmith-project/creduce) can reduce multiple files in one invocation.  I will ask John Regehr if that support is reusable.

**Comment by regehr** [comment]
This is C-Reduce's algorithm:
- repeat until fixpoint
  - for each pass
     - for each non-empty file
        - keep calling the pass until the pass says to stop

A C-Reduce pass is a reduction strategy such as deleting lines, deleting matching braces, inlining functions, collapsing a level of the class hierarchy, etc.  A pass says to stop when it runs out of transformations to try.

This multi-file algorithm is extremely simple. It requires no support from passes. The drawback is that it cannot perform a transformation that requires coordinated changes across multiple files. An example would be eliminating an argument from a function definition and from its callers in other files. It would be nice to support that sort of thing but nobody has explicitly asked for it so far.

**Comment by regehr** [comment]
By the way, people have used C-Reduce to reduce JS programs, apparently with good results. You folks should compare C-Reduce against jsdelta. At the very least it may give you some ideas for areas to improve.

**Comment by xiemaisi** [comment]
I like @esbena's proposed strategy; throwing away entire files where possible sounds like a good plan.

**Comment by esbena** [comment]
Closed by #23
