### ISSUE TITLE
Support for node.js v4 is broken

### ISSUE THREAD

**Issue by msridhar** [wala/jsdelta#42]
CI seems to be broken on node.js v4 and has been for some time.  See this job:

https://travis-ci.org/wala/jsdelta/jobs/636746183

Probably caused by some dependency bump.  Probably we should just drop support for node.js v4.

@esbena thoughts?

**Comment by esbena** [comment]
I am fine with dropping support for v4.

@amoeller @barslev I think you are some of the most active users of this tool - what version of node do you use it with?

**Comment by amoeller** [comment]
We only use newer versions.

**Comment by esbena** [comment]
Changed to 10: https://github.com/wala/jsdelta/commit/6cad172ba8842ff25ddb2304c7562a2e40e7437b 
Lets see if that makes Travis happy.

**Comment by esbena** [comment]
Travis is happy: https://travis-ci.org/wala/jsdelta/builds/637342437

**Comment by msridhar** [comment]
Thanks @esbena!
